# Generated by Django 6.0.2 on 2026-06-22 17:36

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tap_grid", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalLandingPage",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical landing page",
                "verbose_name_plural": "historical landing pages",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPage",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "slug",
                    models.CharField(
                        db_index=True, help_text="Route path starting with /. Example: /my-page", max_length=255
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "layout",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Nested grid layout schema (columns → rows → panel-id slots).",
                    ),
                ),
                (
                    "discoverable",
                    models.BooleanField(
                        default=True,
                        help_text="True if this Page appears in nav-discovery surfaces (palette, chevron popovers, column view, /__nav-index.json). Pages that require URL parameters (e.g. /samsite/finding/<entity_id>) set this False so the discovery surfaces don't link to broken-render URLs. The Page still resolves on direct visit; only browse-style discovery is gated. See spec-web-navigation `req-web-nav-page-discoverable`.",
                    ),
                ),
                (
                    "nav_weight",
                    models.IntegerField(
                        default=0,
                        help_text="Sort-order bias for nav-discovery surfaces. Higher floats up; negative sinks down; 0 means default (alphabetical within tier). Convention: +100..+999 for primary user destinations, 0 for routine pages, -100..-999 for operator/internal pages. Tiebreaker within a tier is alphabetical by name. Applied to the palette tree + ranked-search tiebreaker, chevron popovers, column-view explorer, and /__nav-index.json. See spec-web-navigation `req-web-nav-page-weight`.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical page",
                "verbose_name_plural": "historical pages",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPanel",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        help_text="Kebab-case label used in the HTMX URL alongside the entity UUID. Not globally unique.",
                        max_length=255,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "view",
                    models.CharField(
                        help_text="Template path rendered by the generic panel view. Example: tap_plugins/lotr/templates/character_list.html",
                        max_length=500,
                    ),
                ),
                (
                    "editor_view",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Template path for the panel editor UI. Optional; only set when the panel supports edit mode.",
                        max_length=500,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True, default=dict, help_text="Panel-specific configuration object. Default: {}."
                    ),
                ),
                (
                    "input_vars",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Declared panel input variable names expected at runtime. Default: [].",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical panel",
                "verbose_name_plural": "historical panels",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="LandingPage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s", to="tap_grid.entity"
                    ),
                ),
            ],
            options={
                "db_table": "web_landing_page",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "slug",
                    models.CharField(
                        help_text="Route path starting with /. Example: /my-page", max_length=255, unique=True
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "layout",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Nested grid layout schema (columns → rows → panel-id slots).",
                    ),
                ),
                (
                    "discoverable",
                    models.BooleanField(
                        default=True,
                        help_text="True if this Page appears in nav-discovery surfaces (palette, chevron popovers, column view, /__nav-index.json). Pages that require URL parameters (e.g. /samsite/finding/<entity_id>) set this False so the discovery surfaces don't link to broken-render URLs. The Page still resolves on direct visit; only browse-style discovery is gated. See spec-web-navigation `req-web-nav-page-discoverable`.",
                    ),
                ),
                (
                    "nav_weight",
                    models.IntegerField(
                        default=0,
                        help_text="Sort-order bias for nav-discovery surfaces. Higher floats up; negative sinks down; 0 means default (alphabetical within tier). Convention: +100..+999 for primary user destinations, 0 for routine pages, -100..-999 for operator/internal pages. Tiebreaker within a tier is alphabetical by name. Applied to the palette tree + ranked-search tiebreaker, chevron popovers, column-view explorer, and /__nav-index.json. See spec-web-navigation `req-web-nav-page-weight`.",
                    ),
                ),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s", to="tap_grid.entity"
                    ),
                ),
            ],
            options={
                "db_table": "web_page",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Panel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        help_text="Kebab-case label used in the HTMX URL alongside the entity UUID. Not globally unique.",
                        max_length=255,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "view",
                    models.CharField(
                        help_text="Template path rendered by the generic panel view. Example: tap_plugins/lotr/templates/character_list.html",
                        max_length=500,
                    ),
                ),
                (
                    "editor_view",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Template path for the panel editor UI. Optional; only set when the panel supports edit mode.",
                        max_length=500,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True, default=dict, help_text="Panel-specific configuration object. Default: {}."
                    ),
                ),
                (
                    "input_vars",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Declared panel input variable names expected at runtime. Default: [].",
                    ),
                ),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s", to="tap_grid.entity"
                    ),
                ),
            ],
            options={
                "db_table": "web_panel",
                "abstract": False,
            },
        ),
    ]
