# Generated by Django 6.0.2 on 2026-07-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tap_web", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpanel",
            name="view",
            field=models.CharField(
                help_text="Template path rendered by the generic panel view. Example: tap_plugin/<slug>/templates/<entity>_list.html",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="panel",
            name="view",
            field=models.CharField(
                help_text="Template path rendered by the generic panel view. Example: tap_plugin/<slug>/templates/<entity>_list.html",
                max_length=500,
            ),
        ),
    ]
