# Generated by Django 6.0.2 on 2026-03-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tap_web", "0002_add_page_panel_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="panel",
            name="config",
            field=models.JSONField(default=dict, help_text="Panel-specific configuration object. Default: {}."),
        ),
        migrations.AddField(
            model_name="panel",
            name="editor_css",
            field=models.JSONField(
                default=list, help_text="Flat list of static-relative CSS paths used in panel edit mode. Default: []."
            ),
        ),
        migrations.AddField(
            model_name="panel",
            name="editor_js",
            field=models.JSONField(
                default=list, help_text="Flat list of static-relative JS paths used in panel edit mode. Default: []."
            ),
        ),
        migrations.AddField(
            model_name="panel",
            name="editor_view",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Template path for the panel editor UI. Optional; only set when the panel supports edit mode.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="panel",
            name="input_vars",
            field=models.JSONField(
                default=list, help_text="Declared panel input variable names expected at runtime. Default: []."
            ),
        ),
        migrations.AlterField(
            model_name="panel",
            name="css",
            field=models.JSONField(
                default=list, help_text="Flat list of static-relative CSS paths. Example: ['css/panel.css']"
            ),
        ),
        migrations.AlterField(
            model_name="panel",
            name="js",
            field=models.JSONField(
                default=list, help_text="Flat list of static-relative JS paths. Example: ['js/cytoscape.js']"
            ),
        ),
        migrations.AlterField(
            model_name="panel",
            name="view",
            field=models.CharField(
                help_text="Template path rendered by the generic panel view. Example: tap_plugins/lotr/templates/character_list.html",
                max_length=500,
            ),
        ),
    ]
