# Generated by Django 6.0.2 on 2026-03-18 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tap_web", "0003_panel_edit_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="landingpage",
            old_name="title",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="page",
            old_name="title",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="panel",
            old_name="title",
            new_name="name",
        ),
    ]
