# Generated by Django 6.0.2 on 2026-03-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tap_web", "0006_landingpage_flip_map_page_flip_map_panel_flip_map_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="layout",
            field=models.JSONField(
                blank=True, default=dict, help_text="Nested grid layout schema (columns → rows → panel-id slots)."
            ),
        ),
        migrations.AlterField(
            model_name="panel",
            name="config",
            field=models.JSONField(
                blank=True, default=dict, help_text="Panel-specific configuration object. Default: {}."
            ),
        ),
        migrations.AlterField(
            model_name="panel",
            name="css",
            field=models.JSONField(
                blank=True, default=list, help_text="Flat list of static-relative CSS paths. Example: ['css/panel.css']"
            ),
        ),
        migrations.AlterField(
            model_name="panel",
            name="editor_css",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Flat list of static-relative CSS paths used in panel edit mode. Default: [].",
            ),
        ),
        migrations.AlterField(
            model_name="panel",
            name="editor_js",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Flat list of static-relative JS paths used in panel edit mode. Default: [].",
            ),
        ),
        migrations.AlterField(
            model_name="panel",
            name="input_vars",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Declared panel input variable names expected at runtime. Default: [].",
            ),
        ),
        migrations.AlterField(
            model_name="panel",
            name="js",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Flat list of static-relative JS paths. Example: ['js/cytoscape.js']",
            ),
        ),
    ]
