# Generated by Django 6.0.2 on 2026-04-13 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tap_web", "0008_historicallandingpage_historicalpage_historicalpanel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalpanel",
            name="css",
        ),
        migrations.RemoveField(
            model_name="historicalpanel",
            name="editor_css",
        ),
        migrations.RemoveField(
            model_name="historicalpanel",
            name="editor_js",
        ),
        migrations.RemoveField(
            model_name="historicalpanel",
            name="js",
        ),
        migrations.RemoveField(
            model_name="panel",
            name="css",
        ),
        migrations.RemoveField(
            model_name="panel",
            name="editor_css",
        ),
        migrations.RemoveField(
            model_name="panel",
            name="editor_js",
        ),
        migrations.RemoveField(
            model_name="panel",
            name="js",
        ),
    ]
