# Generated by Django 6.0.2 on 2026-05-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tap_web", "0009_remove_historicalpanel_css_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpage",
            name="discoverable",
            field=models.BooleanField(
                default=True,
                help_text="True if this Page appears in nav-discovery surfaces (palette, chevron popovers, column view, /__nav-index.json). Pages that require URL parameters (e.g. /samsite/finding/<entity_id>) set this False so the discovery surfaces don't link to broken-render URLs. The Page still resolves on direct visit; only browse-style discovery is gated. See spec-web-navigation `req-web-nav-page-discoverable`.",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="discoverable",
            field=models.BooleanField(
                default=True,
                help_text="True if this Page appears in nav-discovery surfaces (palette, chevron popovers, column view, /__nav-index.json). Pages that require URL parameters (e.g. /samsite/finding/<entity_id>) set this False so the discovery surfaces don't link to broken-render URLs. The Page still resolves on direct visit; only browse-style discovery is gated. See spec-web-navigation `req-web-nav-page-discoverable`.",
            ),
        ),
    ]
