# Generated by Django 6.0.2 on 2026-05-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tap_web", "0010_historicalpage_discoverable_page_discoverable"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpage",
            name="nav_weight",
            field=models.IntegerField(
                default=0,
                help_text="Sort-order bias for nav-discovery surfaces. Higher floats up; negative sinks down; 0 means default (alphabetical within tier). Convention: +100..+999 for primary user destinations, 0 for routine pages, -100..-999 for operator/internal pages. Tiebreaker within a tier is alphabetical by name. Applied to the palette tree + ranked-search tiebreaker, chevron popovers, column-view explorer, and /__nav-index.json. See spec-web-navigation `req-web-nav-page-weight`.",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="nav_weight",
            field=models.IntegerField(
                default=0,
                help_text="Sort-order bias for nav-discovery surfaces. Higher floats up; negative sinks down; 0 means default (alphabetical within tier). Convention: +100..+999 for primary user destinations, 0 for routine pages, -100..-999 for operator/internal pages. Tiebreaker within a tier is alphabetical by name. Applied to the palette tree + ranked-search tiebreaker, chevron popovers, column-view explorer, and /__nav-index.json. See spec-web-navigation `req-web-nav-page-weight`.",
            ),
        ),
    ]
