# Generated by Django 6.0.2 on 2026-04-06 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lotr", "0002_add_name_to_lotr_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="title",
        ),
        migrations.RemoveField(
            model_name="historicalcharacter",
            name="title",
        ),
    ]
