# Generated by Django 6.0.2 on 2026-03-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lotr", "0005_historicalcharacter"),
    ]

    operations = [
        migrations.AddField(
            model_name="artifact",
            name="flip_map",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="flip_map",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
            ),
        ),
        migrations.AddField(
            model_name="citadel",
            name="flip_map",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
            ),
        ),
        migrations.AddField(
            model_name="faction",
            name="flip_map",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
            ),
        ),
        migrations.AddField(
            model_name="historicalcharacter",
            name="flip_map",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="flip_map",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
            ),
        ),
        migrations.AddField(
            model_name="race",
            name="flip_map",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
            ),
        ),
        migrations.AddField(
            model_name="sentinel",
            name="flip_map",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
            ),
        ),
        migrations.AddField(
            model_name="wanderer",
            name="flip_map",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
            ),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="batch_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="UUIDv7 of the batch this change was included in.",
                max_length=36,
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="batch_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="UUIDv7 of the batch this change was included in.",
                max_length=36,
            ),
        ),
        migrations.AlterField(
            model_name="citadel",
            name="batch_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="UUIDv7 of the batch this change was included in.",
                max_length=36,
            ),
        ),
        migrations.AlterField(
            model_name="faction",
            name="batch_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="UUIDv7 of the batch this change was included in.",
                max_length=36,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcharacter",
            name="batch_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="UUIDv7 of the batch this change was included in.",
                max_length=36,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="batch_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="UUIDv7 of the batch this change was included in.",
                max_length=36,
            ),
        ),
        migrations.AlterField(
            model_name="race",
            name="batch_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="UUIDv7 of the batch this change was included in.",
                max_length=36,
            ),
        ),
        migrations.AlterField(
            model_name="sentinel",
            name="batch_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="UUIDv7 of the batch this change was included in.",
                max_length=36,
            ),
        ),
        migrations.AlterField(
            model_name="wanderer",
            name="batch_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="UUIDv7 of the batch this change was included in.",
                max_length=36,
            ),
        ),
    ]
