# Generated by Django 6.0.2 on 2026-02-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_examples", "0003_concept_batch_id_precept_batch_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concept",
            name="batch_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="UUIDv7 of the batch this change was included in (FLIP Phase 2).",
                max_length=36,
            ),
        ),
        migrations.AlterField(
            model_name="precept",
            name="batch_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="UUIDv7 of the batch this change was included in (FLIP Phase 2).",
                max_length=36,
            ),
        ),
    ]
