# Generated by Django 6.0.2 on 2026-03-04 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_examples", "0005_historicalconcept"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="concept",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="concept",
            name="originating_grid_id",
        ),
        migrations.RemoveField(
            model_name="concept",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="historicalconcept",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="historicalconcept",
            name="originating_grid_id",
        ),
        migrations.RemoveField(
            model_name="historicalconcept",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="precept",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="precept",
            name="originating_grid_id",
        ),
        migrations.RemoveField(
            model_name="precept",
            name="updated_at",
        ),
    ]
