# Generated by Django 6.0.2 on 2026-02-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_examples", "0002_seed_initial_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="concept",
            name="batch_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="UUIDv7 of the batch this change was included in (FLIP Phase 2).",
                max_length=36,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="precept",
            name="batch_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="UUIDv7 of the batch this change was included in (FLIP Phase 2).",
                max_length=36,
                null=True,
            ),
        ),
    ]
