# Generated by Django 6.0.2 on 2026-05-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aws_core", "0002_cloudfrontdistribution_cloudwatchloggroup_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="acmcertificate",
            name="tags",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="cloudfrontdistribution",
            name="tags",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="cloudwatchloggroup",
            name="tags",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="eventbridgerule",
            name="tags",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="historicalacmcertificate",
            name="tags",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="historicalcloudfrontdistribution",
            name="tags",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="historicalcloudwatchloggroup",
            name="tags",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="historicaleventbridgerule",
            name="tags",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="historicaliamrole",
            name="tags",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="historicallambdafunction",
            name="tags",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="historicalroute53hostedzone",
            name="tags",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="historicals3bucket",
            name="tags",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="iamrole",
            name="tags",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="lambdafunction",
            name="tags",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="route53hostedzone",
            name="tags",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="s3bucket",
            name="tags",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
