# Generated by Django 6.0.2 on 2026-05-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aws_core", "0003_acmcertificate_tags_cloudfrontdistribution_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dynamodbtable",
            name="tags",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="historicaldynamodbtable",
            name="tags",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
