# Generated by Django 6.0.2 on 2026-05-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aws_core", "0005_historicaliamoidcprovider_iamoidcprovider"),
    ]

    operations = [
        migrations.AddField(
            model_name="awsaccount",
            name="tags",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="historicalawsaccount",
            name="tags",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
