# Generated by Django 6.0.2 on 2026-05-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aws_core", "0006_awsaccount_tags_historicalawsaccount_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicals3bucket",
            name="object_count",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicals3bucket",
            name="size_bytes",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicals3bucket",
            name="size_observed_at",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="s3bucket",
            name="object_count",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="s3bucket",
            name="size_bytes",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="s3bucket",
            name="size_observed_at",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
