# Generated by Django 6.0.2 on 2026-07-03 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lotr", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="artifact",
            table="lotr__artifact",
        ),
        migrations.AlterModelTable(
            name="character",
            table="lotr__character",
        ),
        migrations.AlterModelTable(
            name="citadel",
            table="lotr__citadel",
        ),
        migrations.AlterModelTable(
            name="faction",
            table="lotr__faction",
        ),
        migrations.AlterModelTable(
            name="location",
            table="lotr__location",
        ),
        migrations.AlterModelTable(
            name="race",
            table="lotr__race",
        ),
        migrations.AlterModelTable(
            name="realm",
            table="lotr__realm",
        ),
        migrations.AlterModelTable(
            name="sentinel",
            table="lotr__sentinel",
        ),
        migrations.AlterModelTable(
            name="wanderer",
            table="lotr__wanderer",
        ),
    ]
