# Generated by Django 6.0.2 on 2026-06-22 17:36

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="first name")),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="last name")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="email address")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined")),
                (
                    "user_kind",
                    models.CharField(
                        choices=[("human", "Human"), ("program", "Program")],
                        default="human",
                        help_text="Actor kind: 'human' (a person) or 'program' (bootloader, collector, scheduler, AI, ...).",
                        max_length=16,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Backend-managed operator/system context for this actor."
                    ),
                ),
                (
                    "description_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Backend-managed structured context, especially for program/AI actors.",
                    ),
                ),
                (
                    "is_tap_builtin",
                    models.BooleanField(
                        default=False,
                        help_text="True for TAP-managed protected built-in actors (req-tap-auth-builtins).",
                    ),
                ),
                (
                    "tap_builtin_key",
                    models.CharField(
                        blank=True,
                        help_text="Immutable natural key for built-in actors (e.g. 'tap_bootloader'); null for ordinary users. Set only by tap_auth bootstrap/sync code.",
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        blank=True, help_text="When this actor was deactivated, if applicable.", null=True
                    ),
                ),
                (
                    "deactivated_reason",
                    models.TextField(blank=True, default="", help_text="Why this actor was deactivated."),
                ),
                (
                    "deactivated_by_actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="The actor that performed the deactivation, where known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deactivations_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "tap_user",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("is_tap_builtin", False), ("tap_builtin_key__isnull", False), _connector="OR"
                        ),
                        name="tap_auth_builtin_requires_key",
                    )
                ],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
