# Generated by Django 6.0.2 on 2026-07-21 21:36

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import tap_auth.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="first name")),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="last name")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="email address")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined")),
                (
                    "user_kind",
                    models.CharField(
                        choices=[("human", "Human"), ("program", "Program")],
                        default="human",
                        help_text="Actor kind: 'human' (a person) or 'program' (bootloader, collector, scheduler, AI, ...).",
                        max_length=16,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Backend-managed operator/system context for this actor."
                    ),
                ),
                (
                    "description_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Backend-managed structured context, especially for program/AI actors.",
                    ),
                ),
                (
                    "avatar_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Provider profile photo URL (e.g. Google 'picture'), refreshed on login. Display-only; the UI falls back to an initial when empty.",
                        max_length=500,
                    ),
                ),
                (
                    "is_tap_builtin",
                    models.BooleanField(
                        default=False,
                        help_text="True for TAP-managed protected built-in actors (req-tap-auth-builtins).",
                    ),
                ),
                (
                    "tap_builtin_key",
                    models.CharField(
                        blank=True,
                        help_text="Immutable natural key for built-in actors (e.g. 'tap_bootloader'); null for ordinary users. Intended to be set only by tap_auth bootstrap/sync code; immutability is enforced at the application/save() layer.",
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        blank=True, help_text="When this actor was deactivated, if applicable.", null=True
                    ),
                ),
                (
                    "deactivated_reason",
                    models.TextField(blank=True, default="", help_text="Why this actor was deactivated."),
                ),
                (
                    "deactivated_by_actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="The actor that performed the deactivation, where known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deactivations_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "tap_user",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Capability",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Public TAP capability name, e.g. 'grid.read'.", max_length=100, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", help_text="Human-readable meaning of this capability."),
                ),
                (
                    "description_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured context for this capability (synced from tap_auth.capabilities.json), queryable alongside the prose description for AI/security reasoning.",
                    ),
                ),
                (
                    "risk",
                    models.CharField(
                        default="medium",
                        help_text="Risk/classification (low|medium|high|critical) from the registry.",
                        max_length=16,
                    ),
                ),
                (
                    "permission",
                    models.OneToOneField(
                        blank=True,
                        help_text="The projected Django permission this capability is stored as.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tap_capability",
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "capabilities",
                "db_table": "tap_capability",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ExternalIdentity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "provider_id",
                    models.CharField(help_text="Stable provider natural key, e.g. 'example-google'.", max_length=64),
                ),
                ("provider_type", models.CharField(help_text="Provider type, e.g. 'google_oidc'.", max_length=32)),
                (
                    "subject",
                    models.CharField(
                        help_text="Upstream durable subject (OIDC 'sub'). The identity key with provider_id; never logged in full.",
                        max_length=255,
                    ),
                ),
                (
                    "email_snapshot",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Most recent provider-asserted verified email (profile snapshot / hint, NOT identity).",
                        max_length=254,
                    ),
                ),
                (
                    "display_name_snapshot",
                    models.CharField(
                        blank=True, default="", help_text="Most recent provider-asserted display name.", max_length=255
                    ),
                ),
                (
                    "hosted_domain_snapshot",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Most recent returned hosted-domain (Google 'hd') the access decision matched on.",
                        max_length=255,
                    ),
                ),
                (
                    "first_seen",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this external identity was first provisioned."
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        auto_now=True, help_text="When this external identity was last updated (any login touch)."
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this external identity last completed a successful login.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("deactivated", "Deactivated")],
                        default="active",
                        help_text="active | deactivated. Provider/domain removal deactivates affected identities by default.",
                        max_length=16,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The canonical TAP user this external subject resolves to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_identities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "external identities",
                "db_table": "tap_external_identity",
            },
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "public_id",
                    models.CharField(
                        editable=False,
                        help_text="Non-secret public id (kubeadm split): the log-safe lookup/revocation handle. Redemption looks the row up by this, never by the secret (a by-secret query is a timing leak).",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "secret_hash",
                    models.CharField(
                        editable=False,
                        help_text="Plain SHA-256/512 hex of the >=128-bit CSPRNG secret half, verified with a constant-time compare. Deliberately NOT a password KDF (full-entropy secret) and unsalted. Raw secret never stored.",
                        max_length=128,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("enroll_first", "Enroll first passkey (create user)"),
                            ("add_credential", "Add an additional passkey (existing user)"),
                        ],
                        default="enroll_first",
                        help_text="enroll_first (create a new user + first passkey) | add_credential (bind another passkey to an existing user, no new grants).",
                        max_length=16,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Intended identity for an enroll_first invite (profile snapshot, NOT identity). Empty for add_credential.",
                        max_length=254,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Intended display name for an enroll_first invite. Cosmetic.",
                        max_length=255,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Pinned username for an enroll_first redemption (req-tap-auth-passkey-enrollment-8). Empty (the default) derives it from the email via _unique_username. Set when a caller must land the user on an agreed-upon name — canonically the dev bootstrap's fixed `admin` (req-tap-auth-passkey-dev-bootstrap-14). Create-only: a name that already resolves to a User fails loud at mint AND at redeem, never silently becoming an additive mint. Confers no authority — username is a mutable display label, never an identity anchor and never an authorization key (the durable internal User id is the sole consequential selector).",
                        max_length=150,
                    ),
                ),
                (
                    "grants",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Human-assignable role names to apply on redemption (enroll_first only; empty for add_credential). Applied via is_login_grantable + group membership; taken from this server row, never client input.",
                    ),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True, help_text="When this invitation was minted.")),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Hard expiry (short bounded TTL with an enforced maximum). A redeem after this is refused."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("consumed", "Consumed"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        default="pending",
                        help_text="pending -> consumed (successful bind) | expired | revoked. Consumed atomically at credential registration.",
                        max_length=16,
                    ),
                ),
                (
                    "consumed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this invitation was successfully consumed (a passkey bound).",
                        null=True,
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The actor who minted this invitation (a human admin for runtime mints; tap_bootloader for genesis). Audit attribution.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="For add_credential: the existing user the new passkey binds to (bound by stable internal id at mint). Null for enroll_first.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tap_invitation",
            },
        ),
        migrations.CreateModel(
            name="ProtectedGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "builtin_key",
                    models.CharField(
                        help_text="Immutable natural key for the protected group, e.g. 'tap_admin'.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "is_protected",
                    models.BooleanField(
                        default=True, help_text="When true, the group is shielded from ordinary mutation/deletion."
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Human-readable meaning of this role/group (synced from tap_auth.roles.json).",
                    ),
                ),
                (
                    "description_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured context for this role (synced from tap_auth.roles.json), queryable alongside the prose description for AI/security reasoning.",
                    ),
                ),
                (
                    "group",
                    models.OneToOneField(
                        help_text="The Django group this metadata protects.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tap_protected",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "db_table": "tap_protected_group",
                "ordering": ["builtin_key"],
            },
        ),
        migrations.CreateModel(
            name="WebAuthnCredential",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "credential_id",
                    models.CharField(
                        editable=False,
                        help_text="Globally-unique WebAuthn credential id (base64url). A discoverable assertion resolves to exactly one credential/owner via this (req-tap-auth-passkey-webauthn-10).",
                        max_length=1400,
                        unique=True,
                    ),
                ),
                (
                    "public_key",
                    models.CharField(
                        editable=False,
                        help_text="COSE public key (base64url). Public material only — the private key never leaves the authenticator.",
                        max_length=1024,
                    ),
                ),
                (
                    "sign_count",
                    models.PositiveBigIntegerField(
                        default=0,
                        help_text="Last verified signature counter; the new count is persisted after each assertion. A regression is a cloned-authenticator signal, hard-denied by py_webauthn (0/0 no-counter authenticators are exempt) (req-tap-auth-passkey-webauthn-8).",
                    ),
                ),
                (
                    "aaguid",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Authenticator model id (UUID string). Best-effort under attestation=none; '' or all-zeros '00000000-0000-0000-0000-000000000000' = unknown. NOT used for the synced-vs-device-bound determination (that rides BE/BS).",
                        max_length=36,
                    ),
                ),
                (
                    "transports",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Client-reported transports (e.g. ['internal','hybrid','usb']). Advisory hint for the next ceremony.",
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("single_device", "Single-device (device-bound)"),
                            ("multi_device", "Multi-device (backup-eligible / syncable)"),
                        ],
                        default="single_device",
                        help_text="BE-derived (py_webauthn credential_device_type): single_device (device-bound, no sync safety net — nudge escalates) vs multi_device (backup-eligible/syncable). Reliable under attestation=none.",
                        max_length=16,
                    ),
                ),
                (
                    "backed_up",
                    models.BooleanField(
                        default=False,
                        help_text="BS flag (py_webauthn credential_backed_up): whether the credential is CURRENTLY backed up / synced. Mutable across assertions; reliable under attestation=none.",
                    ),
                ),
                (
                    "device_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Human-friendly device name (e.g. 'MacBook Touch ID'). Cosmetic; operator/UI-supplied.",
                        max_length=128,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, help_text="When this passkey was registered.")),
                (
                    "last_used",
                    models.DateTimeField(
                        blank=True, help_text="When this passkey last completed a successful assertion.", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The TAP user who owns this passkey.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webauthn_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tap_webauthn_credential",
            },
        ),
        migrations.CreateModel(
            name="WebAuthnUserHandle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "handle",
                    models.CharField(
                        default=tap_auth.models._new_webauthn_user_handle,
                        editable=False,
                        help_text="Opaque, non-PII WebAuthn user handle: 64 CSPRNG bytes, hex. Never email/username.",
                        max_length=128,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, help_text="When this handle was minted.")),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The TAP user this opaque handle identifies in WebAuthn ceremonies.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webauthn_handle",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tap_webauthn_user_handle",
            },
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("is_tap_builtin", True), ("tap_builtin_key__isnull", False)),
                    models.Q(("is_tap_builtin", False), ("tap_builtin_key__isnull", True)),
                    _connector="OR",
                ),
                name="tap_auth_builtin_key_iff_builtin",
            ),
        ),
        migrations.AddIndex(
            model_name="externalidentity",
            index=models.Index(fields=["email_snapshot"], name="tap_extid_email_idx"),
        ),
        migrations.AddConstraint(
            model_name="externalidentity",
            constraint=models.UniqueConstraint(
                fields=("provider_id", "subject"), name="tap_external_identity_provider_subject_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(fields=["status"], name="tap_invitation_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="invitation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("action", "add_credential"), ("target_user__isnull", False)),
                    models.Q(("action", "enroll_first"), ("target_user__isnull", True)),
                    _connector="OR",
                ),
                name="tap_invitation_target_iff_add_credential",
            ),
        ),
        migrations.AddIndex(
            model_name="webauthncredential",
            index=models.Index(fields=["user"], name="tap_webauthn_cred_user_idx"),
        ),
    ]
