# Generated by Django 6.0.2 on 2026-06-22 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("tap_auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Capability",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Public TAP capability name, e.g. 'grid.read'.", max_length=100, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", help_text="Human-readable meaning of this capability."),
                ),
                (
                    "risk",
                    models.CharField(
                        default="medium",
                        help_text="Risk/classification (low|medium|high|critical) from the registry.",
                        max_length=16,
                    ),
                ),
                (
                    "permission",
                    models.OneToOneField(
                        blank=True,
                        help_text="The projected Django permission this capability is stored as.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tap_capability",
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "capabilities",
                "db_table": "tap_capability",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProtectedGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "builtin_key",
                    models.CharField(
                        help_text="Immutable natural key for the protected group, e.g. 'tap_admin'.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "is_protected",
                    models.BooleanField(
                        default=True, help_text="When true, the group is shielded from ordinary mutation/deletion."
                    ),
                ),
                (
                    "group",
                    models.OneToOneField(
                        help_text="The Django group this metadata protects.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tap_protected",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "db_table": "tap_protected_group",
                "ordering": ["builtin_key"],
            },
        ),
    ]
