# Generated by Django 6.0.2 on 2026-06-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("tap_auth", "0002_capability_protectedgroup"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="tap_auth_builtin_requires_key",
        ),
        migrations.AlterField(
            model_name="user",
            name="tap_builtin_key",
            field=models.CharField(
                blank=True,
                help_text="Immutable natural key for built-in actors (e.g. 'tap_bootloader'); null for ordinary users. Intended to be set only by tap_auth bootstrap/sync code; immutability is enforced at the application/save() layer.",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("is_tap_builtin", True), ("tap_builtin_key__isnull", False)),
                    models.Q(("is_tap_builtin", False), ("tap_builtin_key__isnull", True)),
                    _connector="OR",
                ),
                name="tap_auth_builtin_key_iff_builtin",
            ),
        ),
    ]
