# Generated by Django 6.0.2 on 2026-06-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tap_auth", "0003_remove_user_tap_auth_builtin_requires_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="capability",
            name="description_json",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Structured context for this capability (synced from tap_auth.capabilities.json), queryable alongside the prose description for AI/security reasoning.",
            ),
        ),
        migrations.AddField(
            model_name="protectedgroup",
            name="description",
            field=models.TextField(
                blank=True, default="", help_text="Human-readable meaning of this role/group (synced from tap_auth.roles.json)."
            ),
        ),
        migrations.AddField(
            model_name="protectedgroup",
            name="description_json",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Structured context for this role (synced from tap_auth.roles.json), queryable alongside the prose description for AI/security reasoning.",
            ),
        ),
    ]
