# Generated by Django 6.0.2 on 2026-06-25 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tap_auth", "0004_capability_description_json_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalIdentity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "provider_id",
                    models.CharField(
                        help_text="Stable provider natural key, e.g. 'criticalsec-google'.", max_length=64
                    ),
                ),
                ("provider_type", models.CharField(help_text="Provider type, e.g. 'google_oidc'.", max_length=32)),
                (
                    "subject",
                    models.CharField(
                        help_text="Upstream durable subject (OIDC 'sub'). The identity key with provider_id; never logged in full.",
                        max_length=255,
                    ),
                ),
                (
                    "email_snapshot",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Most recent provider-asserted verified email (profile snapshot / hint, NOT identity).",
                        max_length=254,
                    ),
                ),
                (
                    "display_name_snapshot",
                    models.CharField(
                        blank=True, default="", help_text="Most recent provider-asserted display name.", max_length=255
                    ),
                ),
                (
                    "hosted_domain_snapshot",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Most recent returned hosted-domain (Google 'hd') the access decision matched on.",
                        max_length=255,
                    ),
                ),
                (
                    "first_seen",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this external identity was first provisioned."
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        auto_now=True, help_text="When this external identity was last updated (any login touch)."
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this external identity last completed a successful login.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("deactivated", "Deactivated")],
                        default="active",
                        help_text="active | deactivated. Provider/domain removal deactivates affected identities by default.",
                        max_length=16,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The canonical TAP user this external subject resolves to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_identities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "external identities",
                "db_table": "tap_external_identity",
                "indexes": [models.Index(fields=["email_snapshot"], name="tap_extid_email_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider_id", "subject"), name="tap_external_identity_provider_subject_unique"
                    )
                ],
            },
        ),
    ]
