# Generated by Django 6.0.2 on 2026-06-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tap_auth", "0005_externalidentity"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Provider profile photo URL (e.g. Google 'picture'), refreshed on login. Display-only; the UI falls back to an initial when empty.",
                max_length=500,
            ),
        ),
    ]
