# Generated by Django 6.0.2 on 2026-07-09 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import tap_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ("tap_auth", "0006_user_avatar_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebAuthnUserHandle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "handle",
                    models.CharField(
                        default=tap_auth.models._new_webauthn_user_handle,
                        editable=False,
                        help_text="Opaque, non-PII WebAuthn user handle: 64 CSPRNG bytes, hex. Never email/username.",
                        max_length=128,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, help_text="When this handle was minted.")),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The TAP user this opaque handle identifies in WebAuthn ceremonies.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webauthn_handle",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tap_webauthn_user_handle",
            },
        ),
        migrations.CreateModel(
            name="WebAuthnCredential",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "credential_id",
                    models.CharField(
                        editable=False,
                        help_text="Globally-unique WebAuthn credential id (base64url). A discoverable assertion resolves to exactly one credential/owner via this (req-tap-auth-passkey-webauthn-10).",
                        max_length=1400,
                        unique=True,
                    ),
                ),
                (
                    "public_key",
                    models.CharField(
                        editable=False,
                        help_text="COSE public key (base64url). Public material only — the private key never leaves the authenticator.",
                        max_length=1024,
                    ),
                ),
                (
                    "sign_count",
                    models.PositiveBigIntegerField(
                        default=0,
                        help_text="Last verified signature counter; the new count is persisted after each assertion. A regression is a cloned-authenticator signal, hard-denied by py_webauthn (0/0 no-counter authenticators are exempt) (req-tap-auth-passkey-webauthn-8).",
                    ),
                ),
                (
                    "aaguid",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Authenticator model id (UUID string). Best-effort under attestation=none; '' or all-zeros '00000000-0000-0000-0000-000000000000' = unknown. NOT used for the synced-vs-device-bound determination (that rides BE/BS).",
                        max_length=36,
                    ),
                ),
                (
                    "transports",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Client-reported transports (e.g. ['internal','hybrid','usb']). Advisory hint for the next ceremony.",
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("single_device", "Single-device (device-bound)"),
                            ("multi_device", "Multi-device (backup-eligible / syncable)"),
                        ],
                        default="single_device",
                        help_text="BE-derived (py_webauthn credential_device_type): single_device (device-bound, no sync safety net — nudge escalates) vs multi_device (backup-eligible/syncable). Reliable under attestation=none.",
                        max_length=16,
                    ),
                ),
                (
                    "backed_up",
                    models.BooleanField(
                        default=False,
                        help_text="BS flag (py_webauthn credential_backed_up): whether the credential is CURRENTLY backed up / synced. Mutable across assertions; reliable under attestation=none.",
                    ),
                ),
                (
                    "device_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Human-friendly device name (e.g. 'MacBook Touch ID'). Cosmetic; operator/UI-supplied.",
                        max_length=128,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, help_text="When this passkey was registered.")),
                (
                    "last_used",
                    models.DateTimeField(
                        blank=True, help_text="When this passkey last completed a successful assertion.", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The TAP user who owns this passkey.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webauthn_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tap_webauthn_credential",
                "indexes": [models.Index(fields=["user"], name="tap_webauthn_cred_user_idx")],
            },
        ),
    ]
