# Generated by Django 6.0.2 on 2026-07-09 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tap_auth", "0007_webauthnuserhandle_webauthncredential"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "public_id",
                    models.CharField(
                        editable=False,
                        help_text="Non-secret public id (kubeadm split): the log-safe lookup/revocation handle. Redemption looks the row up by this, never by the secret (a by-secret query is a timing leak).",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "secret_hash",
                    models.CharField(
                        editable=False,
                        help_text="Plain SHA-256/512 hex of the >=128-bit CSPRNG secret half, verified with a constant-time compare. Deliberately NOT a password KDF (full-entropy secret) and unsalted. Raw secret never stored.",
                        max_length=128,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("enroll_first", "Enroll first passkey (create user)"),
                            ("add_credential", "Add an additional passkey (existing user)"),
                        ],
                        default="enroll_first",
                        help_text="enroll_first (create a new user + first passkey) | add_credential (bind another passkey to an existing user, no new grants).",
                        max_length=16,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Intended identity for an enroll_first invite (profile snapshot, NOT identity). Empty for add_credential.",
                        max_length=254,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Intended display name for an enroll_first invite. Cosmetic.",
                        max_length=255,
                    ),
                ),
                (
                    "grants",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Human-assignable role names to apply on redemption (enroll_first only; empty for add_credential). Applied via is_login_grantable + group membership; taken from this server row, never client input.",
                    ),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True, help_text="When this invitation was minted.")),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Hard expiry (short bounded TTL with an enforced maximum). A redeem after this is refused."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("consumed", "Consumed"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        default="pending",
                        help_text="pending -> consumed (successful bind) | expired | revoked. Consumed atomically at credential registration.",
                        max_length=16,
                    ),
                ),
                (
                    "consumed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this invitation was successfully consumed (a passkey bound).",
                        null=True,
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The actor who minted this invitation (a human admin for runtime mints; tap_bootloader for genesis). Audit attribution.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="For add_credential: the existing user the new passkey binds to (bound by stable internal id at mint). Null for enroll_first.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tap_invitation",
                "indexes": [models.Index(fields=["status"], name="tap_invitation_status_idx")],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("action", "add_credential"), ("target_user__isnull", False)),
                            models.Q(("action", "enroll_first"), ("target_user__isnull", True)),
                            _connector="OR",
                        ),
                        name="tap_invitation_target_iff_add_credential",
                    )
                ],
            },
        ),
    ]
