# Generated by Django 6.0.2 on 2026-02-05 17:13

import django.db.models.deletion
import tap_core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tap_core", "0002_entity_entitytype_edge"),
    ]

    operations = [
        migrations.CreateModel(
            name="Concept",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "originating_grid_id",
                    models.UUIDField(blank=True, default=tap_core.models.get_default_grid_id, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("summary", models.TextField(blank=True, default="")),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s", to="tap_core.entity"
                    ),
                ),
            ],
            options={
                "db_table": "test_plugin_concept",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Precept",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "originating_grid_id",
                    models.UUIDField(blank=True, default=tap_core.models.get_default_grid_id, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("statement", models.TextField(blank=True, default="")),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s", to="tap_core.entity"
                    ),
                ),
            ],
            options={
                "db_table": "test_plugin_precept",
                "abstract": False,
            },
        ),
    ]
