# Generated by Django 6.0.2 on 2026-02-10 22:11

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models

import tap_grid.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tap_grid", "0004_alter_edge_batch_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "originating_grid_id",
                    models.UUIDField(blank=True, default=tap_grid.models.get_default_grid_id, null=True),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in (FLIP Phase 2).",
                        max_length=36,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed"), ("failed", "Failed")],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Source identifier (e.g., 'scanner:aws', 'import:csv', 'api:v1').",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Free-form metadata about the batch (parameters, counts, etc.).",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True, help_text="When the batch was opened.")),
                (
                    "closed_at",
                    models.DateTimeField(blank=True, help_text="When the batch was closed or failed.", null=True),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", help_text="Error details if status is 'failed'."),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who initiated the batch (if applicable).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s", to="tap_grid.entity"
                    ),
                ),
            ],
            options={
                "db_table": "tap_batch",
                "ordering": ["-started_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricalBatch",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                (
                    "originating_grid_id",
                    models.UUIDField(blank=True, default=tap_grid.models.get_default_grid_id, null=True),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in (FLIP Phase 2).",
                        max_length=36,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed"), ("failed", "Failed")],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Source identifier (e.g., 'scanner:aws', 'import:csv', 'api:v1').",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Free-form metadata about the batch (parameters, counts, etc.).",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, editable=False, help_text="When the batch was opened."),
                ),
                (
                    "closed_at",
                    models.DateTimeField(blank=True, help_text="When the batch was closed or failed.", null=True),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", help_text="Error details if status is 'failed'."),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="User who initiated the batch (if applicable).",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical batch",
                "verbose_name_plural": "historical batchs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="BatchEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("link", "Link (edge creation)"),
                            ("unlink", "Unlink (edge deletion)"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "entity_id",
                    models.UUIDField(db_index=True, help_text="The Entity that was affected by this operation."),
                ),
                (
                    "entity_type",
                    models.CharField(
                        db_index=True, help_text="Type of the affected entity (for quick filtering).", max_length=255
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ORM model class name if applicable (e.g., 'Concept').",
                        max_length=255,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, help_text="Additional context (edge endpoints, etc.)."),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batch_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="events", to="tap_flip.batch"
                    ),
                ),
            ],
            options={
                "db_table": "tap_batch_event",
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(fields=["batch", "timestamp"], name="idx_batchevent_batch_ts"),
                    models.Index(fields=["entity_id", "timestamp"], name="idx_batchevent_entity_ts"),
                ],
            },
        ),
    ]
