# Generated by Django 6.0.2 on 2026-03-04 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tap_flip", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batch",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="batch",
            name="originating_grid_id",
        ),
        migrations.RemoveField(
            model_name="batch",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="historicalbatch",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="historicalbatch",
            name="originating_grid_id",
        ),
        migrations.RemoveField(
            model_name="historicalbatch",
            name="updated_at",
        ),
    ]
