# Generated by Django 6.0.2 on 2026-02-06 21:40

import django.db.models.deletion
from django.db import migrations, models

import tap_grid.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tap_grid", "0002_entity_entitytype_edge"),
    ]

    operations = [
        migrations.CreateModel(
            name="Layout",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "originating_grid_id",
                    models.UUIDField(blank=True, default=tap_grid.models.get_default_grid_id, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "cytoscape_config",
                    models.JSONField(
                        blank=True, default=dict, help_text="Full Cytoscape.js config: nodes, edges, positions, style."
                    ),
                ),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s", to="tap_grid.entity"
                    ),
                ),
            ],
            options={
                "db_table": "tap_layout",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
