# Generated by Django 6.0.2 on 2026-06-22 17:36

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tap_grid", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Arrangement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "definition",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Declarative arrangement rule: anchor, members, positioning, distribution.",
                    ),
                ),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s", to="tap_grid.entity"
                    ),
                ),
            ],
            options={
                "db_table": "tap_arrangement",
                "ordering": ["-entity__created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Elevation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "definition",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Elevation definition: zoom, layouts (ordered IDs), double_tap_targets.",
                    ),
                ),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s", to="tap_grid.entity"
                    ),
                ),
            ],
            options={
                "db_table": "tap_elevation",
                "ordering": ["-entity__created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricalArrangement",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "definition",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Declarative arrangement rule: anchor, members, positioning, distribution.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical arrangement",
                "verbose_name_plural": "historical arrangements",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalElevation",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "definition",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Elevation definition: zoom, layouts (ordered IDs), double_tap_targets.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical elevation",
                "verbose_name_plural": "historical elevations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalLayout",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "definition",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Layout definition: optional js_file (layout_module) and/or arrangements (ordered IDs).",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical layout",
                "verbose_name_plural": "historical layouts",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProjection",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "definition",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Projection definition: elevations (ordered IDs), default_elevation_id, chrome.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical projection",
                "verbose_name_plural": "historical projections",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Layout",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "definition",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Layout definition: optional js_file (layout_module) and/or arrangements (ordered IDs).",
                    ),
                ),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s", to="tap_grid.entity"
                    ),
                ),
            ],
            options={
                "db_table": "tap_layout",
                "ordering": ["-entity__created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Projection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "definition",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Projection definition: elevations (ordered IDs), default_elevation_id, chrome.",
                    ),
                ),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s", to="tap_grid.entity"
                    ),
                ),
            ],
            options={
                "db_table": "tap_projection",
                "ordering": ["-entity__created_at"],
                "abstract": False,
            },
        ),
    ]
