# Generated by Django 6.0.2 on 2026-03-04 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tap_viz", "0003_alter_layout_batch_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="layout",
            options={"ordering": ["-entity__created_at"]},
        ),
        migrations.RemoveField(
            model_name="layout",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="layout",
            name="originating_grid_id",
        ),
        migrations.RemoveField(
            model_name="layout",
            name="updated_at",
        ),
    ]
