# Generated by Django 6.0.2 on 2026-03-23 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tap_viz", "0004_alter_layout_options_remove_layout_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="layout",
            name="cytoscape_config",
        ),
        migrations.AddField(
            model_name="layout",
            name="definition",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="TAP-owned declarative layout payload: inputs, steps, presentation, interactions.",
            ),
        ),
    ]
