# Generated by Django 6.0.2 on 2026-02-07 03:37

import django.db.models.deletion
from django.db import migrations, models

import tap_core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tap_core", "0002_entity_entitytype_edge"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artifact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "originating_grid_id",
                    models.UUIDField(blank=True, default=tap_core.models.get_default_grid_id, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("power", models.TextField(blank=True, default="")),
                ("origin", models.CharField(blank=True, default="", max_length=255)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s", to="tap_core.entity"
                    ),
                ),
            ],
            options={
                "db_table": "lotr_artifact",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "originating_grid_id",
                    models.UUIDField(blank=True, default=tap_core.models.get_default_grid_id, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bio", models.TextField(blank=True, default="")),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s", to="tap_core.entity"
                    ),
                ),
            ],
            options={
                "db_table": "lotr_character",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Citadel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "originating_grid_id",
                    models.UUIDField(blank=True, default=tap_core.models.get_default_grid_id, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fortification", models.TextField(blank=True, default="")),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s", to="tap_core.entity"
                    ),
                ),
            ],
            options={
                "db_table": "lotr_citadel",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Faction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "originating_grid_id",
                    models.UUIDField(blank=True, default=tap_core.models.get_default_grid_id, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("purpose", models.TextField(blank=True, default="")),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s", to="tap_core.entity"
                    ),
                ),
            ],
            options={
                "db_table": "lotr_faction",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "originating_grid_id",
                    models.UUIDField(blank=True, default=tap_core.models.get_default_grid_id, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True, default="")),
                ("realm", models.CharField(blank=True, default="", max_length=255)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s", to="tap_core.entity"
                    ),
                ),
            ],
            options={
                "db_table": "lotr_location",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Race",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "originating_grid_id",
                    models.UUIDField(blank=True, default=tap_core.models.get_default_grid_id, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("homeland", models.CharField(blank=True, default="", max_length=255)),
                ("traits", models.TextField(blank=True, default="")),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s", to="tap_core.entity"
                    ),
                ),
            ],
            options={
                "db_table": "lotr_race",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Sentinel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "originating_grid_id",
                    models.UUIDField(blank=True, default=tap_core.models.get_default_grid_id, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("watch_domain", models.TextField(blank=True, default="")),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s", to="tap_core.entity"
                    ),
                ),
            ],
            options={
                "db_table": "lotr_sentinel",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Wanderer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "originating_grid_id",
                    models.UUIDField(blank=True, default=tap_core.models.get_default_grid_id, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("journey", models.TextField(blank=True, default="")),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s", to="tap_core.entity"
                    ),
                ),
            ],
            options={
                "db_table": "lotr_wanderer",
                "abstract": False,
            },
        ),
    ]
