# Generated by Django 6.0.2 on 2026-02-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lotr", "0002_artifact_batch_id_character_batch_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifact",
            name="batch_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="UUIDv7 of the batch this change was included in (FLIP Phase 2).",
                max_length=36,
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="batch_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="UUIDv7 of the batch this change was included in (FLIP Phase 2).",
                max_length=36,
            ),
        ),
        migrations.AlterField(
            model_name="citadel",
            name="batch_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="UUIDv7 of the batch this change was included in (FLIP Phase 2).",
                max_length=36,
            ),
        ),
        migrations.AlterField(
            model_name="faction",
            name="batch_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="UUIDv7 of the batch this change was included in (FLIP Phase 2).",
                max_length=36,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="batch_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="UUIDv7 of the batch this change was included in (FLIP Phase 2).",
                max_length=36,
            ),
        ),
        migrations.AlterField(
            model_name="race",
            name="batch_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="UUIDv7 of the batch this change was included in (FLIP Phase 2).",
                max_length=36,
            ),
        ),
        migrations.AlterField(
            model_name="sentinel",
            name="batch_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="UUIDv7 of the batch this change was included in (FLIP Phase 2).",
                max_length=36,
            ),
        ),
        migrations.AlterField(
            model_name="wanderer",
            name="batch_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="UUIDv7 of the batch this change was included in (FLIP Phase 2).",
                max_length=36,
            ),
        ),
    ]
