# Generated by Django 6.0.2 on 2026-03-04 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lotr", "0003_alter_artifact_batch_id_alter_character_batch_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artifact",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="artifact",
            name="originating_grid_id",
        ),
        migrations.RemoveField(
            model_name="artifact",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="character",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="character",
            name="originating_grid_id",
        ),
        migrations.RemoveField(
            model_name="character",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="citadel",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="citadel",
            name="originating_grid_id",
        ),
        migrations.RemoveField(
            model_name="citadel",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="faction",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="faction",
            name="originating_grid_id",
        ),
        migrations.RemoveField(
            model_name="faction",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="location",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="location",
            name="originating_grid_id",
        ),
        migrations.RemoveField(
            model_name="location",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="race",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="race",
            name="originating_grid_id",
        ),
        migrations.RemoveField(
            model_name="race",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="sentinel",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="sentinel",
            name="originating_grid_id",
        ),
        migrations.RemoveField(
            model_name="sentinel",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="wanderer",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="wanderer",
            name="originating_grid_id",
        ),
        migrations.RemoveField(
            model_name="wanderer",
            name="updated_at",
        ),
    ]
