# Generated by Django 6.0.2 on 2026-02-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tap_core", "0002_entity_entitytype_edge"),
    ]

    operations = [
        migrations.AddField(
            model_name="edge",
            name="batch_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="UUIDv7 of the batch this change was included in (FLIP Phase 2).",
                max_length=36,
                null=True,
            ),
        ),
    ]
