# Generated by Django 6.0.2 on 2026-05-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tap_cares", "0002_collectionjob_historicalcollectionjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionjob",
            name="grift_batches",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="historicalcollectionjob",
            name="grift_batches",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
