# Generated by Django 6.0.2 on 2026-05-12 21:34

import tap_cares.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tap_cares", "0004_collectionjob_results_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionjob",
            name="grift_batches",
            field=models.JSONField(blank=True, default=tap_cares.models._empty_grift_batches),
        ),
        migrations.AlterField(
            model_name="historicalcollectionjob",
            name="grift_batches",
            field=models.JSONField(blank=True, default=tap_cares.models._empty_grift_batches),
        ),
    ]
