# Generated by Django 6.0.2 on 2026-05-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tap_cares", "0004_collectionjob_results_and_more"),
    ]

    # `grift_batches` default was `tap_cares.models._empty_grift_batches`, a
    # callable since removed when the field was dropped in favor of
    # PRODUCED_BATCH edges (req-grid-edge-produced-batch). Inlined to `dict`
    # here so this historical migration stays importable; the field is removed
    # by a later migration, so the exact historical default is immaterial.
    operations = [
        migrations.AlterField(
            model_name="collectionjob",
            name="grift_batches",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="historicalcollectionjob",
            name="grift_batches",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
