# Generated by Django 6.0.2 on 2026-05-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tap_cares", "0007_historicalschedule_historicalschedulefire_schedule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionjob",
            name="manual_run",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="collectionjob",
            name="manual_run_source",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="historicalcollectionjob",
            name="manual_run",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="historicalcollectionjob",
            name="manual_run_source",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
