# Generated by Django 6.0.2 on 2026-05-16 13:36

from django.db import migrations, models

import tap_cares.models


class Migration(migrations.Migration):

    dependencies = [
        ("tap_cares", "0008_collectionjob_manual_run_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionjob",
            name="run_mode",
            field=models.CharField(
                choices=[("full", "Full"), ("self_test_only", "Self-test only")],
                db_index=True,
                default="full",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="collectionjob",
            name="self_test",
            field=models.JSONField(blank=True, default=tap_cares.models._empty_self_test),
        ),
        migrations.AddField(
            model_name="historicalcollectionjob",
            name="run_mode",
            field=models.CharField(
                choices=[("full", "Full"), ("self_test_only", "Self-test only")],
                db_index=True,
                default="full",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="historicalcollectionjob",
            name="self_test",
            field=models.JSONField(blank=True, default=tap_cares.models._empty_self_test),
        ),
    ]
