# Generated by Django 6.0.2 on 2026-06-11 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tap_cares", "0009_collectionjob_run_mode_collectionjob_self_test_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collectionjob",
            name="grift_batches",
        ),
        migrations.RemoveField(
            model_name="historicalcollectionjob",
            name="grift_batches",
        ),
    ]
