# Generated by Django 6.0.2 on 2026-02-05 16:55

import uuid

import django.db.models.deletion
from django.db import migrations, models

import tap_grid.models


class Migration(migrations.Migration):

    dependencies = [
        ("tap_grid", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entity",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                (
                    "entity_type",
                    models.CharField(
                        db_index=True,
                        help_text="Type slug (e.g. 'server', 'control'). Validated at service layer.",
                        max_length=255,
                    ),
                ),
                ("display_name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "originating_grid_id",
                    models.UUIDField(blank=True, db_index=True, default=tap_grid.models.get_default_grid_id, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Entities",
                "db_table": "tap_entity",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EntityType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.CharField(max_length=255, unique=True)),
                ("display_name", models.CharField(max_length=255)),
                ("icon", models.CharField(blank=True, default="", max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("plugin_name", models.CharField(blank=True, db_index=True, default="", max_length=255)),
            ],
            options={
                "db_table": "tap_entity_type",
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="Edge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "originating_grid_id",
                    models.UUIDField(blank=True, default=tap_grid.models.get_default_grid_id, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("edge_type", models.CharField(db_index=True, max_length=255)),
                ("properties", models.JSONField(blank=True, default=dict)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s", to="tap_grid.entity"
                    ),
                ),
                (
                    "from_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="edges_out", to="tap_grid.entity"
                    ),
                ),
                (
                    "to_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="edges_in", to="tap_grid.entity"
                    ),
                ),
            ],
            options={
                "db_table": "tap_edge",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(fields=["from_entity", "edge_type"], name="idx_edge_from_type"),
                    models.Index(fields=["to_entity", "edge_type"], name="idx_edge_to_type"),
                ],
            },
        ),
    ]
