# Generated by Django 6.0.8 on 2026-08-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tap_grid", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entitytype",
            name="kind",
            field=models.CharField(
                blank=True,
                choices=[("node", "Node"), ("edge", "Edge")],
                db_index=True,
                default="",
                help_text="Whether this type describes a node or an edge; empty means not yet classified.",
                max_length=16,
            ),
        ),
    ]
