# Generated by Django 6.0.2 on 2026-03-04 22:21

import django.contrib.postgres.indexes
import django.db.models.deletion
import tap_grid.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tap_grid", "0004_alter_edge_batch_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dimension",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "originating_grid_id",
                    models.UUIDField(blank=True, default=tap_grid.models.get_default_grid_id, null=True),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in (FLIP Phase 2).",
                        max_length=36,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "tap_dimension",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="entity",
            name="dimensions",
            field=models.JSONField(
                default=dict, help_text="Flat namespace dict for partitioning/scoping (e.g. {'tap.graph': 'web'})."
            ),
        ),
        migrations.AddIndex(
            model_name="entity",
            index=django.contrib.postgres.indexes.GinIndex(fields=["dimensions"], name="idx_entity_dimensions_gin"),
        ),
        migrations.AddField(
            model_name="dimension",
            name="entity",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s", to="tap_grid.entity"
            ),
        ),
    ]
