# Generated by Django 6.0.2 on 2026-03-04 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tap_grid", "0005_dimension_entity_dimensions_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="edge",
            options={"ordering": ["-entity__created_at"]},
        ),
        migrations.RemoveField(
            model_name="dimension",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="dimension",
            name="originating_grid_id",
        ),
        migrations.RemoveField(
            model_name="dimension",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="edge",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="edge",
            name="originating_grid_id",
        ),
        migrations.RemoveField(
            model_name="edge",
            name="updated_at",
        ),
    ]
