# Generated by Django 6.0.2 on 2026-03-09 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tap_grid", "0006_alter_edge_options_remove_dimension_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Search",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in (FLIP Phase 2).",
                        max_length=36,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("search_type", models.CharField(max_length=50)),
                ("root", models.CharField(max_length=50)),
                ("definition", models.JSONField(default=dict)),
                ("input_schema", models.JSONField(blank=True, null=True)),
                ("returns", models.JSONField(blank=True, null=True)),
                ("default_limit", models.IntegerField(blank=True, null=True)),
                ("max_limit", models.IntegerField(blank=True, null=True)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s", to="tap_grid.entity"
                    ),
                ),
            ],
            options={
                "db_table": "tap_search",
                "abstract": False,
            },
        ),
    ]
