# Generated by Django 6.0.2 on 2026-03-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tap_grid", "0007_search"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistryProxy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "verbose_name": "Registry",
                "verbose_name_plural": "Registries",
                "managed": False,
            },
        ),
    ]
