# Generated by Django 6.0.2 on 2026-03-18 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tap_grid", "0008_registry_proxy_admin_view"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entity",
            old_name="display_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="entitytype",
            old_name="display_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="search",
            old_name="title",
            new_name="name",
        ),
    ]
