# Generated by Django 6.0.2 on 2026-03-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tap_grid", "0010_drop_core_examples_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="dimension",
            name="flip_map",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
            ),
        ),
        migrations.AddField(
            model_name="edge",
            name="flip_map",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
            ),
        ),
        migrations.AddField(
            model_name="search",
            name="flip_map",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
            ),
        ),
        migrations.AlterField(
            model_name="dimension",
            name="batch_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="UUIDv7 of the batch this change was included in.",
                max_length=36,
            ),
        ),
        migrations.AlterField(
            model_name="edge",
            name="batch_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="UUIDv7 of the batch this change was included in.",
                max_length=36,
            ),
        ),
        migrations.AlterField(
            model_name="search",
            name="batch_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="UUIDv7 of the batch this change was included in.",
                max_length=36,
            ),
        ),
    ]
