# Generated by Django 6.0.2 on 2026-03-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tap_grid", "0011_dimension_flip_map_edge_flip_map_search_flip_map_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="search",
            name="definition",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
