# Generated by Django 6.0.2 on 2026-03-31 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tap_grid", "0013_batch_historicalbatch_historicaldimension_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="description",
            field=models.TextField(blank=True, default="", help_text="Long-form description of the batch purpose."),
        ),
        migrations.AddField(
            model_name="batch",
            name="description_json",
            field=models.JSONField(
                blank=True, help_text="Structured description payload with format and data keys.", null=True
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="title",
            field=models.CharField(blank=True, default="", help_text="Human-readable batch summary.", max_length=255),
        ),
        migrations.AddField(
            model_name="historicalbatch",
            name="description",
            field=models.TextField(blank=True, default="", help_text="Long-form description of the batch purpose."),
        ),
        migrations.AddField(
            model_name="historicalbatch",
            name="description_json",
            field=models.JSONField(
                blank=True, help_text="Structured description payload with format and data keys.", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalbatch",
            name="title",
            field=models.CharField(blank=True, default="", help_text="Human-readable batch summary.", max_length=255),
        ),
    ]
