# Generated by Django 6.0.2 on 2026-03-31 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tap_grid", "0014_batch_metadata_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, db_index=True, help_text="Set when the entity is tombstoned. Null means live.", null=True
            ),
        ),
    ]
