# Generated by Django 6.0.2 on 2026-03-31 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tap_grid", "0015_tombstone_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="version",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Monotonic revision counter. Increments on every canonical mutation, including tombstone.",
            ),
        ),
    ]
