# Generated by Django 6.0.2 on 2026-04-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tap_grid", "0018_alter_batch_name_alter_historicalbatch_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("link", "Link (edge creation)"),
                    ("unlink", "Unlink (edge deletion)"),
                    ("force_reimport", "Force Re-Import"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
